print ("Why did the scarecrow win an award?")
input ("")
print("because he was outstanding in his field")
input("")
print("okay lets do another")
print("What has four weels and flies?")
input("")
print("A garbage truck")
print(r"\        /              /")
print(r" \      /              /")
  print(r"\    /              /")
   print(r"\  /"             /)
  print(r"  \/")
print(r"      |")
print(r"      |")
print(r"      |")
print(r"      |")
print(r"      |")